version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: budget_db
    environment:
      POSTGRES_USER: jepoyqt
      POSTGRES_PASSWORD: hidalgo001
      POSTGRES_DB: budgetdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
